---
title: "Analyzing Interruption and Blaming in Legislative Deliberation Process in South Korea, Welfare and Public Health Committee"
author: "Inhwan Ko"
date: 'Sep 17th, 2020'
output: html_document
---

1. Load necessary packages

```{r}
# rm(list=ls())
# install.packages(c("tm","backports","tidyverse","tidytext","topicmodels","stringr","lda"))

library(tidyverse)
library(tidytext)
library(topicmodels)
library(tm)
library(stringr)
library(lda)

Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre1.8.0_261")
# install.packages("rJava")
library(rJava)

# remotes::install_github("haven-jeon/KoNLP", upgrade="never", INSTALL_opts=c("--no-multiarch"))
library(KoNLP)
library(readxl)

```


2. Load data

```{r}
speech_wel16 <- read_excel("wel_final/wel16.xlsx")[,-1]
speech_wel17 <- read_excel("wel_final/wel17.xlsx")[,-1]
speech_wel18 <- read_excel("wel_final/wel18.xlsx")[,-1]
speech_wel19 <- read_excel("wel_final/wel19.xlsx")[,-1]
speech_wel20 <- read_excel("wel_final/wel20.xlsx")[,-1]
```

3. Operationalize

1) Numbering

```{r}
speech_wel16$no <- speech_wel17$no <- speech_wel18$no <- speech_wel19$no <- speech_wel20$no <- NA

speech_wel16$no <- c(1:nrow(speech_wel16)) 
speech_wel17$no <- c(1:nrow(speech_wel17))
speech_wel18$no <- c(1:nrow(speech_wel18))
speech_wel19$no <- c(1:nrow(speech_wel19))
speech_wel20$no <- c(1:nrow(speech_wel20))
```

2) Legislator or not (1-0)- binary

```{r}
speech_wel16$legis <- speech_wel17$legis <- speech_wel18$legis <- speech_wel19$legis <- speech_wel20$legis <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$legis[i] <- ifelse(
   sum(grep("의원", speech_wel16$speaker[i]))==1 |
   sum(grep("위원", speech_wel16$speaker[i]))==1 |
   sum(grep("위원장", speech_wel16$speaker[i]))==1 |
   sum(grep("委員", speech_wel16$speaker[i]))==1 |
   sum(grep("議員", speech_wel16$speaker[i]))==1 |
   sum(grep("議員長", speech_wel16$speaker[i]))==1 |
   sum(grep("위원장대리", speech_wel16$speaker[i]))==1 |
   sum(grep("議員長代理", speech_wel16$speaker[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$legis[i] <- ifelse(
   sum(grep("의원", speech_wel17$speaker[i]))==1 |
   sum(grep("위원", speech_wel17$speaker[i]))==1 |
   sum(grep("위원장", speech_wel17$speaker[i]))==1 |
   sum(grep("委員", speech_wel17$speaker[i]))==1 |
   sum(grep("議員", speech_wel17$speaker[i]))==1 |
   sum(grep("議員長", speech_wel17$speaker[i]))==1 |
   sum(grep("위원장대리", speech_wel17$speaker[i]))==1 |
   sum(grep("議員長代理", speech_wel17$speaker[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel18)) {
  speech_wel18$legis[i] <- ifelse(
   sum(grep("의원", speech_wel18$speaker[i]))==1 |
   sum(grep("위원", speech_wel18$speaker[i]))==1 |
   sum(grep("위원장", speech_wel18$speaker[i]))==1 |
   sum(grep("委員", speech_wel18$speaker[i]))==1 |
   sum(grep("議員", speech_wel18$speaker[i]))==1 |
   sum(grep("議員長", speech_wel18$speaker[i]))==1 |
   sum(grep("위원장대리", speech_wel18$speaker[i]))==1 |
   sum(grep("議員長代理", speech_wel18$speaker[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel19)) {
  speech_wel19$legis[i] <- ifelse(
   sum(grep("의원", speech_wel19$speaker[i]))==1 |
   sum(grep("위원", speech_wel19$speaker[i]))==1 |
   sum(grep("위원장", speech_wel19$speaker[i]))==1 |
   sum(grep("委員", speech_wel19$speaker[i]))==1 |
   sum(grep("議員", speech_wel19$speaker[i]))==1 |
   sum(grep("議員長", speech_wel19$speaker[i]))==1 |
   sum(grep("위원장대리", speech_wel19$speaker[i]))==1 |
   sum(grep("議員長代理", speech_wel19$speaker[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel20)) {
  speech_wel20$legis[i] <- ifelse(
   sum(grep("의원", speech_wel20$speaker[i]))==1 |
   sum(grep("위원", speech_wel20$speaker[i]))==1 |
   sum(grep("위원장", speech_wel20$speaker[i]))==1 |
   sum(grep("委員", speech_wel20$speaker[i]))==1 |
   sum(grep("議員", speech_wel20$speaker[i]))==1 |
   sum(grep("議員長", speech_wel20$speaker[i]))==1 |
   sum(grep("위원장대리", speech_wel20$speaker[i]))==1 |
   sum(grep("議員長代理", speech_wel20$speaker[i]))==1, 
  1,0
 )
}

sum(speech_wel16$legis) #10984 / 18335, 0.5990
sum(speech_wel17$legis) #22697 / 35141, 0.6458
sum(speech_wel18$legis) #24635 / 38282, 0.6435
sum(speech_wel19$legis) #41138 / 63451, 0.6483
sum(speech_wel20$legis) #16241 / 24628, 0.6594

```

3) Interruption (by parcing out "......")

```{r}

speech_wel16$interrupt <- speech_wel17$interrupt <- speech_wel18$interrupt <- speech_wel19$interrupt <- speech_wel20$interrupt <- NA

speech_wel16$interrupt[1] <- speech_wel17$interrupt[1] <- speech_wel18$interrupt[1] <- speech_wel19$interrupt[1] <- speech_wel20$interrupt[1] <- 0

for (i in 2:length(speech_wel16$speech)) {
  speech_wel16$interrupt[i] <- ifelse(
   sum(grep("……$", speech_wel16$speech[i-1]))==1, 
   1, 0
   )
}

for (i in 2:length(speech_wel17$speech)) {
  speech_wel17$interrupt[i] <- ifelse(
   sum(grep("……$", speech_wel17$speech[i-1]))==1, 
   1, 0
   )
}

for (i in 2:length(speech_wel18$speech)) {
  speech_wel18$interrupt[i] <- ifelse(
   sum(grep("……$", speech_wel18$speech[i-1]))==1, 
   1, 0
   )
}

for (i in 2:length(speech_wel19$speech)) {
  speech_wel19$interrupt[i] <- ifelse(
   sum(grep("……$", speech_wel19$speech[i-1]))==1, 
   1, 0
   )
}

for (i in 2:length(speech_wel20$speech)) {
  speech_wel20$interrupt[i] <- ifelse(
   sum(grep("……$", speech_wel20$speech[i-1]))==1, 
   1, 0
   )
}

sum(speech_wel16$interrupt[speech_wel16$legis==1])
sum(speech_wel17$interrupt[speech_wel17$legis==1])
sum(speech_wel18$interrupt[speech_wel18$legis==1])
sum(speech_wel19$interrupt[speech_wel19$legis==1])
sum(speech_wel20$interrupt[speech_wel20$legis==1])

```

4) Blaming (using dictionary method) 

```{r}
speech_wel16$blame <- speech_wel17$blame <- speech_wel18$blame <- speech_wel19$blame <- speech_wel20$blame <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$blame[i] <- ifelse(
   sum(grep("바보", speech_wel16$speech[i]))==1 |
   sum(grep("멍청", speech_wel16$speech[i]))==1 |
   sum(grep("무식", speech_wel16$speech[i]))==1 |
   sum(grep("경박", speech_wel16$speech[i]))==1 |
   sum(grep("인격", speech_wel16$speech[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$blame[i] <- ifelse(
   sum(grep("바보", speech_wel17$speech[i]))==1 |
   sum(grep("멍청", speech_wel17$speech[i]))==1 |
   sum(grep("무식", speech_wel17$speech[i]))==1 |
   sum(grep("경박", speech_wel17$speech[i]))==1 |
   sum(grep("인격", speech_wel17$speech[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel18)) {
  speech_wel18$blame[i] <- ifelse(
   sum(grep("바보", speech_wel18$speech[i]))==1 |
   sum(grep("멍청", speech_wel18$speech[i]))==1 |
   sum(grep("무식", speech_wel18$speech[i]))==1 |
   sum(grep("경박", speech_wel18$speech[i]))==1 |
   sum(grep("인격", speech_wel18$speech[i]))==1, 
  1,0
 )
}
for (i in 1:nrow(speech_wel19)) {
  speech_wel19$blame[i] <- ifelse(
   sum(grep("바보", speech_wel19$speech[i]))==1 |
   sum(grep("멍청", speech_wel19$speech[i]))==1 |
   sum(grep("무식", speech_wel19$speech[i]))==1 |
   sum(grep("경박", speech_wel19$speech[i]))==1 |
   sum(grep("인격", speech_wel19$speech[i]))==1, 
  1,0
 )
}
for (i in 1:nrow(speech_wel20)) {
  speech_wel20$blame[i] <- ifelse(
   sum(grep("바보", speech_wel20$speech[i]))==1 |
   sum(grep("멍청", speech_wel20$speech[i]))==1 |
   sum(grep("무식", speech_wel20$speech[i]))==1 |
   sum(grep("경박", speech_wel20$speech[i]))==1 |
   sum(grep("인격", speech_wel20$speech[i]))==1, 
  1,0
 )
}

sum(speech_wel16$blame[speech_wel16$legis==1])
sum(speech_wel17$blame[speech_wel17$legis==1])
sum(speech_wel18$blame[speech_wel18$legis==1])
sum(speech_wel19$blame[speech_wel19$legis==1])
sum(speech_wel20$blame[speech_wel20$legis==1])

```

5) Criticizing the assembly

```{r}

speech_wel16$critique <- speech_wel17$critique <- speech_wel18$critique <- speech_wel19$critique <- speech_wel20$critique <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$critique[i] <- ifelse(
   sum(grep("파행", speech_wel16$speech[i]))==1 |
   sum(grep("막장", speech_wel16$speech[i]))==1 |
   sum(grep("전횡", speech_wel16$speech[i]))==1 |
   sum(grep("독단", speech_wel16$speech[i]))==1 |
   sum(grep("날치기", speech_wel16$speech[i]))==1 |
   sum(grep("깽판", speech_wel16$speech[i]))==1  , 
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$critique[i] <- ifelse(
   sum(grep("파행", speech_wel16$speech[i]))==1 |
   sum(grep("막장", speech_wel16$speech[i]))==1 |
   sum(grep("전횡", speech_wel16$speech[i]))==1 |
   sum(grep("독단", speech_wel16$speech[i]))==1 |
   sum(grep("날치기", speech_wel16$speech[i]))==1 |
   sum(grep("깽판", speech_wel16$speech[i]))==1  , 
  1,0
 )
}
for (i in 1:nrow(speech_wel18)) {
  speech_wel18$critique[i] <- ifelse(
   sum(grep("파행", speech_wel16$speech[i]))==1 |
   sum(grep("막장", speech_wel16$speech[i]))==1 |
   sum(grep("전횡", speech_wel16$speech[i]))==1 |
   sum(grep("독단", speech_wel16$speech[i]))==1 |
   sum(grep("날치기", speech_wel16$speech[i]))==1 |
   sum(grep("깽판", speech_wel16$speech[i]))==1  , 
  1,0
 )
}
for (i in 1:nrow(speech_wel19)) {
  speech_wel19$critique[i] <- ifelse(
   sum(grep("파행", speech_wel16$speech[i]))==1 |
   sum(grep("막장", speech_wel16$speech[i]))==1 |
   sum(grep("전횡", speech_wel16$speech[i]))==1 |
   sum(grep("독단", speech_wel16$speech[i]))==1 |
   sum(grep("날치기", speech_wel16$speech[i]))==1 |
   sum(grep("깽판", speech_wel16$speech[i]))==1  , 
  1,0
 )
}
for (i in 1:nrow(speech_wel20)) {
  speech_wel20$critique[i] <- ifelse(
   sum(grep("파행", speech_wel16$speech[i]))==1 |
   sum(grep("막장", speech_wel16$speech[i]))==1 |
   sum(grep("전횡", speech_wel16$speech[i]))==1 |
   sum(grep("독단", speech_wel16$speech[i]))==1 |
   sum(grep("날치기", speech_wel16$speech[i]))==1 |
   sum(grep("깽판", speech_wel16$speech[i]))==1  , 
  1,0
 )
}

sum(speech_wel16$critique[speech_wel16$legis==1])
sum(speech_wel17$critique[speech_wel17$legis==1])
sum(speech_wel18$critique[speech_wel18$legis==1])
sum(speech_wel19$critique[speech_wel19$legis==1])
sum(speech_wel20$critique[speech_wel20$legis==1])

```

6) Criticizing the government

```{r}

speech_wel16$critgov <- speech_wel17$critgov <- speech_wel18$critgov <- speech_wel19$critgov <- speech_wel20$critgov <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$critgov[i] <- ifelse(
   sum(grep("독재", speech_wel16$speech[i]))==1 |
   sum(grep("사퇴", speech_wel16$speech[i]))==1, 
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$critgov[i] <- ifelse(
   sum(grep("독재", speech_wel16$speech[i]))==1 |
   sum(grep("사퇴", speech_wel16$speech[i]))==1, 
  1,0
 )
}
for (i in 1:nrow(speech_wel18)) {
  speech_wel18$critgov[i] <- ifelse(
   sum(grep("독재", speech_wel16$speech[i]))==1 |
   sum(grep("사퇴", speech_wel16$speech[i]))==1, 
  1,0
 )
}
for (i in 1:nrow(speech_wel19)) {
  speech_wel19$critgov[i] <- ifelse(
   sum(grep("독재", speech_wel16$speech[i]))==1 |
   sum(grep("사퇴", speech_wel16$speech[i]))==1, 
  1,0
 )
}
for (i in 1:nrow(speech_wel20)) {
  speech_wel20$critgov[i] <- ifelse(
   sum(grep("독재", speech_wel16$speech[i]))==1 |
   sum(grep("사퇴", speech_wel16$speech[i]))==1, 
  1,0
 )
}

sum(speech_wel16$critgov[speech_wel16$legis==1])
sum(speech_wel17$critgov[speech_wel17$legis==1])
sum(speech_wel18$critgov[speech_wel18$legis==1])
sum(speech_wel19$critgov[speech_wel19$legis==1])
sum(speech_wel20$critgov[speech_wel20$legis==1])

```

7) Misinformation


```{r}

speech_wel16$misinfo <- speech_wel17$misinfo <- speech_wel18$misinfo <- speech_wel19$misinfo <- speech_wel20$misinfo <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$misinfo[i] <- ifelse(
   sum(grep("왜곡", speech_wel16$speech[i]))==1 |
   sum(grep("거짓", speech_wel16$speech[i]))==1 |
   sum(grep("선동", speech_wel16$speech[i]))==1 , 
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$misinfo[i] <- ifelse(
   sum(grep("왜곡", speech_wel16$speech[i]))==1 |
   sum(grep("거짓", speech_wel16$speech[i]))==1 |
   sum(grep("선동", speech_wel16$speech[i]))==1 , 
  1,0
 )
}
for (i in 1:nrow(speech_wel18)) {
  speech_wel18$misinfo[i] <- ifelse(
   sum(grep("왜곡", speech_wel16$speech[i]))==1 |
   sum(grep("거짓", speech_wel16$speech[i]))==1 |
   sum(grep("선동", speech_wel16$speech[i]))==1 , 
  1,0
 )
}
for (i in 1:nrow(speech_wel19)) {
  speech_wel19$misinfo[i] <- ifelse(
   sum(grep("왜곡", speech_wel16$speech[i]))==1 |
   sum(grep("거짓", speech_wel16$speech[i]))==1 |
   sum(grep("선동", speech_wel16$speech[i]))==1 , 
  1,0
 )
}
for (i in 1:nrow(speech_wel20)) {
  speech_wel20$misinfo[i] <- ifelse(
   sum(grep("왜곡", speech_wel16$speech[i]))==1 |
   sum(grep("거짓", speech_wel16$speech[i]))==1 |
   sum(grep("선동", speech_wel16$speech[i]))==1 , 
  1,0
 )
}

sum(speech_wel16$misinfo[speech_wel16$legis==1])
sum(speech_wel17$misinfo[speech_wel17$legis==1])
sum(speech_wel18$misinfo[speech_wel18$legis==1])
sum(speech_wel19$misinfo[speech_wel19$legis==1])
sum(speech_wel20$misinfo[speech_wel20$legis==1])

```

8) Total condemnation

```{r}

speech_wel16$totalcondemn <- speech_wel17$totalcondemn <- speech_wel18$totalcondemn <- speech_wel19$totalcondemn <- speech_wel20$totalcondemn <- 0

for (i in 1:nrow(speech_wel16)) {
  speech_wel16$totalcondemn[i] <- ifelse(
   speech_wel16$blame[i]==1 |
   speech_wel16$critique[i]==1 |
   speech_wel16$critgov[i]==1 |
   speech_wel16$misinfo[i]==1,
  1,0
 )
}

for (i in 1:nrow(speech_wel17)) {
  speech_wel17$totalcondemn[i] <- ifelse(
   speech_wel17$blame[i]==1 |
   speech_wel17$critique[i]==1 |
   speech_wel17$critgov[i]==1 |
   speech_wel17$misinfo[i]==1,
  1,0
 )
}
for (i in 1:nrow(speech_wel18)) {
  speech_wel18$totalcondemn[i] <- ifelse(
   speech_wel18$blame[i]==1 |
   speech_wel18$critique[i]==1 |
   speech_wel18$critgov[i]==1 |
   speech_wel18$misinfo[i]==1,
  1,0
 )
}
for (i in 1:nrow(speech_wel19)) {
  speech_wel19$totalcondemn[i] <- ifelse(
   speech_wel19$blame[i]==1 |
   speech_wel19$critique[i]==1 |
   speech_wel19$critgov[i]==1 |
   speech_wel19$misinfo[i]==1,
  1,0
 )
}
for (i in 1:nrow(speech_wel20)) {
  speech_wel20$totalcondemn[i] <- ifelse(
   speech_wel20$blame[i]==1 |
   speech_wel20$critique[i]==1 |
   speech_wel20$critgov[i]==1 |
   speech_wel20$misinfo[i]==1,
  1,0
 )
}

sum(speech_wel16$totalcondemn[speech_wel16$legis==1])
sum(speech_wel17$totalcondemn[speech_wel17$legis==1])
sum(speech_wel18$totalcondemn[speech_wel18$legis==1])
sum(speech_wel19$totalcondemn[speech_wel19$legis==1])
sum(speech_wel20$totalcondemn[speech_wel20$legis==1])
```

